### ISSUE TITLE
version command not working

### ISSUE THREAD

**Issue by PhilippIRL** [CodeCanna/petfacts-rust#1]
When I try to run `petfacts version` it just panics with the error message:
```
thread 'main' panicked at 'Couldn't find Cargo.toml, this is a major problem: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\PhilippIRL\.cargo\registry\src\github.com-1ecc6299db9ec823\petfacts-0.1.1\src/main.rs:22:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by AdriDevelopsThings** [comment]
Instead of reading the version from the `Cargo.toml` file, you could use `env!("CARGO_PKG_VERSION")` that compiles the supplied version in the `Cargo.toml` to your executable.

**Comment by CodeCanna** [comment]
Oh wow!  First let me say that this is the first time anyone has EVER interacted with any of my projects enough to send me a issue request!!!!  I'm so excited this is my first issue request not opened by me.

I'm working on this now :)

**Comment by CodeCanna** [comment]
> Instead of reading the version from the `Cargo.toml` file, you could use `env!("CARGO_PKG_VERSION")` that compiles the supplied version in the `Cargo.toml` to your executable.

I didn't know about this thank you for this, I'm new at Rust and I just hard-coded the version which is not ideal, so I'm going to implement this instead.

**Comment by CodeCanna** [comment]
`env!("CARGO_PKG_VERSION"` worked like a charm thanks a lot for the input!  I've pushed this update to crates.io and it seems to working just fine.
